-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: EmailRequest.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/emailrequest (
  email VARCHAR(255) NOT NULL,
  request LONGTEXT NOT NULL,
  PRIMARY KEY(email)
) /*$wgDBTableOptions*/;
